//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.04 at 12:01:24 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dmg.org/PMML-4_3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dmg.pmml_4_3;
